/**
 * Instrumento semilla del Knowledge Pack E-commerce v0.1 (sección 7).
 * 16 preguntas condicionales, con su variable estructurada asociada.
 * Solo datos: la interfaz nunca declara preguntas ni opciones.
 */

import type { PreguntaKB } from "../tipos";
import { redesActivas, tiendaActiva, tiendaEnMarcha } from "./condicionales";

export const preguntas: PreguntaKB[] = [
  /* ---------------- EC · Contexto del canal (siempre visibles) --------------- */
  {
    id: "EC-Q01",
    dominio: "EC",
    tema: "Estado del canal",
    texto:
      "¿Actualmente su empresa vende directamente productos o servicios a través de una tienda online?",
    tipo: "unica",
    variableId: "EC-V01",
    variable: "ecommerce_status",
    opciones: [
      { valor: "si", etiqueta: "Sí" },
      { valor: "no", etiqueta: "No" },
      { valor: "en_implementacion", etiqueta: "Está en implementación" },
    ],
    ayuda: "Esta respuesta define qué bloques del instrumento aplican a su empresa.",
  },
  {
    id: "EC-Q02",
    dominio: "EC",
    tema: "Modelo comercial",
    texto: "¿A quién vende principalmente a través de canales digitales?",
    tipo: "unica",
    variableId: "EC-V02",
    variable: "commerce_model",
    opciones: [
      { valor: "consumidor_final", etiqueta: "Consumidor final" },
      { valor: "empresas", etiqueta: "Empresas" },
      { valor: "ambos", etiqueta: "Ambos" },
      { valor: "otro", etiqueta: "Otro" },
    ],
  },
  {
    id: "EC-Q03",
    dominio: "EC",
    tema: "Relevancia",
    texto: "¿Qué importancia tiene actualmente el canal digital para las ventas de la empresa?",
    tipo: "unica",
    variableId: "EC-V03",
    variable: "digital_sales_relevance",
    opciones: [
      { valor: "no_genera", etiqueta: "No genera ventas" },
      { valor: "complementario", etiqueta: "Complementario" },
      { valor: "importante", etiqueta: "Importante" },
      { valor: "principal", etiqueta: "Principal" },
      { valor: "no_sabemos", etiqueta: "No lo sabemos", desconoce: true },
    ],
  },

  /* ---------------- TEC · Adecuación tecnológica (LC-02) -------------------- */
  {
    id: "TEC-Q01",
    dominio: "TEC",
    tema: "Capacidad técnica",
    texto:
      "¿Cómo describiría la capacidad de su empresa para administrar técnicamente su plataforma de e-commerce?",
    tipo: "unica",
    variableId: "TEC-V01",
    variable: "technical_capacity",
    condicionalId: "LC-02",
    visibleSi: tiendaEnMarcha,
    opciones: [
      { valor: "terceros", etiqueta: "Dependemos de terceros" },
      { valor: "basica", etiqueta: "Básica" },
      { valor: "equipo_tecnico", etiqueta: "Contamos con equipo técnico" },
      { valor: "avanzada", etiqueta: "Avanzada" },
      { valor: "no_sabemos", etiqueta: "No sabemos", desconoce: true },
    ],
  },
  {
    id: "TEC-Q02",
    dominio: "TEC",
    tema: "Integraciones",
    texto: "¿La tienda necesita intercambiar información con otros sistemas?",
    tipo: "multiple",
    variableId: "TEC-V02",
    variable: "integration_needs",
    condicionalId: "LC-02",
    visibleSi: tiendaEnMarcha,
    opciones: [
      { valor: "inventario", etiqueta: "Inventario" },
      { valor: "erp", etiqueta: "ERP" },
      { valor: "crm", etiqueta: "CRM" },
      { valor: "facturacion", etiqueta: "Facturación" },
      { valor: "logistica", etiqueta: "Logística" },
      { valor: "pagos", etiqueta: "Pagos" },
      { valor: "marketplaces", etiqueta: "Marketplaces" },
      { valor: "otros", etiqueta: "Otros" },
      { valor: "ninguno", etiqueta: "Ninguno" },
      { valor: "no_sabemos", etiqueta: "No sabemos", desconoce: true },
    ],
    ayuda: "Puede seleccionar varias opciones.",
  },
  {
    id: "TEC-Q03",
    dominio: "TEC",
    tema: "Inventario",
    texto: "¿Cómo administra actualmente el inventario relacionado con las ventas digitales?",
    tipo: "unica",
    variableId: "TEC-V03",
    variable: "inventory_management",
    condicionalId: "LC-02",
    visibleSi: tiendaEnMarcha,
    opciones: [
      { valor: "manual", etiqueta: "Manual" },
      { valor: "excel", etiqueta: "Excel" },
      { valor: "plataforma", etiqueta: "En la plataforma de la tienda" },
      { valor: "sistema", etiqueta: "Sistema especializado" },
      { valor: "erp_integrado", etiqueta: "ERP integrado" },
      { valor: "no_aplica", etiqueta: "No aplica" },
      { valor: "no_sabemos", etiqueta: "No sabemos", desconoce: true },
    ],
  },
  {
    id: "TEC-Q04",
    dominio: "TEC",
    tema: "Personalización",
    texto:
      "¿Qué tan importante es modificar profundamente la experiencia o funcionalidades de la tienda?",
    tipo: "unica",
    variableId: "TEC-V04",
    variable: "customization_need",
    condicionalId: "LC-02",
    visibleSi: tiendaEnMarcha,
    opciones: [
      { valor: "baja", etiqueta: "Baja" },
      { valor: "media", etiqueta: "Media" },
      { valor: "alta", etiqueta: "Alta" },
      { valor: "no_sabemos", etiqueta: "No sabemos", desconoce: true },
    ],
  },

  /* ---------------- SS · Social Selling (LC-03) ----------------------------- */
  {
    id: "SS-Q01",
    dominio: "SS",
    tema: "Uso de redes",
    texto: "¿Para qué utiliza actualmente las redes sociales de la empresa?",
    tipo: "multiple",
    variableId: "SS-V01",
    variable: "social_use",
    opciones: [
      { valor: "marca", etiqueta: "Presencia de marca" },
      { valor: "contenido", etiqueta: "Publicar contenido" },
      { valor: "servicio", etiqueta: "Atención y servicio" },
      { valor: "conversaciones", etiqueta: "Conversaciones con clientes" },
      { valor: "prospectos", etiqueta: "Identificar prospectos" },
      { valor: "venta", etiqueta: "Vender" },
      { valor: "senales", etiqueta: "Detectar señales de interés" },
      { valor: "sin_proposito", etiqueta: "Sin propósito definido" },
    ],
    ayuda: "Puede seleccionar varias opciones. Habilita el bloque de Social Selling.",
  },
  {
    id: "SS-Q02",
    dominio: "SS",
    tema: "Proceso",
    texto:
      "Cuando una persona muestra interés mediante redes sociales, ¿existe un proceso definido para continuar la conversación?",
    tipo: "unica",
    variableId: "SS-V02",
    variable: "followup_process",
    condicionalId: "LC-03",
    visibleSi: redesActivas,
    opciones: [
      { valor: "si", etiqueta: "Sí" },
      { valor: "parcialmente", etiqueta: "Parcialmente" },
      { valor: "no", etiqueta: "No" },
      { valor: "no_sabemos", etiqueta: "No sabemos", desconoce: true },
    ],
  },
  {
    id: "SS-Q03",
    dominio: "SS",
    tema: "Registro",
    texto: "¿Las oportunidades comerciales originadas en redes quedan registradas?",
    tipo: "unica",
    variableId: "SS-V03",
    variable: "opportunity_tracking",
    condicionalId: "LC-03",
    visibleSi: redesActivas,
    opciones: [
      { valor: "crm", etiqueta: "En un CRM" },
      { valor: "sistema", etiqueta: "En otro sistema" },
      { valor: "excel", etiqueta: "En Excel" },
      { valor: "whatsapp", etiqueta: "En WhatsApp" },
      { valor: "depende_vendedor", etiqueta: "Depende de cada vendedor" },
      { valor: "no_registran", etiqueta: "No se registran" },
    ],
  },
  {
    id: "SS-Q04",
    dominio: "SS",
    tema: "Contenido útil",
    texto:
      "¿El contenido publicado ayuda al cliente a comprender problemas o tomar decisiones, además de promocionar productos?",
    tipo: "unica",
    variableId: "SS-V04",
    variable: "useful_content",
    condicionalId: "LC-03",
    visibleSi: redesActivas,
    opciones: [
      { valor: "frecuentemente", etiqueta: "Frecuentemente" },
      { valor: "algunas_veces", etiqueta: "Algunas veces" },
      { valor: "promocional", etiqueta: "Principalmente promocional" },
      { valor: "no_publicamos", etiqueta: "No publicamos" },
      { valor: "no_sabemos", etiqueta: "No sabemos", desconoce: true },
    ],
  },
  {
    id: "SS-Q05",
    dominio: "SS",
    tema: "Medición",
    texto: "¿Miden qué ocurre después de una interacción social?",
    tipo: "unica",
    variableId: "SS-V05",
    variable: "outcome_measurement",
    condicionalId: "LC-03",
    visibleSi: redesActivas,
    opciones: [
      { valor: "hasta_venta", etiqueta: "Hasta la venta" },
      { valor: "conversaciones_leads", etiqueta: "Conversaciones o leads" },
      { valor: "metricas_redes", etiqueta: "Solo métricas de redes" },
      { valor: "no", etiqueta: "No" },
      { valor: "no_sabemos", etiqueta: "No sabemos", desconoce: true },
    ],
  },

  /* ---------------- CRO · Journey transaccional (LC-01 / LC-02) ------------- */
  {
    id: "CRO-Q01",
    dominio: "CRO",
    tema: "Conversión",
    texto: "¿La empresa mide actualmente la conversión de su tienda online?",
    tipo: "unica",
    variableId: "CRO-V01",
    variable: "conversion_measurement",
    condicionalId: "LC-01",
    visibleSi: tiendaActiva,
    opciones: [
      { valor: "por_etapas", etiqueta: "Por etapas del proceso" },
      { valor: "general", etiqueta: "Conversión general" },
      { valor: "solo_ventas", etiqueta: "Solo ventas" },
      { valor: "no", etiqueta: "No" },
      { valor: "no_sabemos", etiqueta: "No sabemos", desconoce: true },
    ],
  },
  {
    id: "CRO-Q02",
    dominio: "CRO",
    tema: "Abandono",
    texto: "¿Revisan de forma sistemática dónde abandonan los usuarios el proceso de compra?",
    tipo: "unica",
    variableId: "CRO-V02",
    variable: "abandonment_analysis",
    condicionalId: "LC-01",
    visibleSi: tiendaActiva,
    opciones: [
      { valor: "si", etiqueta: "Sí" },
      { valor: "ocasionalmente", etiqueta: "Ocasionalmente" },
      { valor: "no", etiqueta: "No" },
      { valor: "no_sabemos", etiqueta: "No sabemos", desconoce: true },
    ],
  },
  {
    id: "CRO-Q03",
    dominio: "CRO",
    tema: "Optimización",
    texto:
      "¿Se realizan mejoras periódicas en la tienda basadas en datos, pruebas o comportamiento?",
    tipo: "unica",
    variableId: "CRO-V03",
    variable: "optimization_practice",
    condicionalId: "LC-01",
    visibleSi: tiendaActiva,
    opciones: [
      { valor: "sistematicamente", etiqueta: "Sistemáticamente" },
      { valor: "ocasionalmente", etiqueta: "Ocasionalmente" },
      { valor: "percepcion", etiqueta: "Por percepción" },
      { valor: "no", etiqueta: "No" },
      { valor: "no_sabemos", etiqueta: "No sabemos", desconoce: true },
    ],
  },
  {
    id: "CRO-Q04",
    dominio: "CRO",
    tema: "Etapa problemática",
    texto: "¿En qué etapa considera que existen mayores dificultades?",
    tipo: "unica",
    variableId: "CRO-V04",
    variable: "perceived_friction_stage",
    condicionalId: "LC-01",
    visibleSi: tiendaActiva,
    opciones: [
      { valor: "home", etiqueta: "Home" },
      { valor: "categorias", etiqueta: "Categorías" },
      { valor: "producto", etiqueta: "Producto" },
      { valor: "landing", etiqueta: "Landing" },
      { valor: "carrito", etiqueta: "Carrito" },
      { valor: "checkout", etiqueta: "Checkout" },
      { valor: "postcompra", etiqueta: "Postcompra" },
      { valor: "no_sabemos", etiqueta: "No sabemos", desconoce: true },
    ],
  },
];

export const etiquetasOpcion = new Map<string, string>(
  preguntas.flatMap((p) => p.opciones.map((o) => [`${p.id}:${o.valor}`, o.etiqueta]))
);
