/**
 * Catálogo de reglas del motor (POC-04, sección 8).
 * Las reglas son datos versionados: condiciones declarativas, evidencia, severidad,
 * política de confianza, clave de mensaje y factores de priorización.
 * Añadir una regla no requiere modificar la interfaz.
 */

import type { Regla } from "./tipos";

export const RULESET_VERSION = "1.0.0";

export const reglas: Regla[] = [
  /* ---------------- D01 · Estrategia y liderazgo ---------------- */
  {
    ruleId: "RK-EST-001",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D01", capacidadId: "CAP-D01-01" },
    conditions: {
      tipo: "alguna",
      condiciones: [
        { tipo: "respuestaMenorIgual", questionId: "Q01", valor: 2 },
        { tipo: "respuestaMenorIgual", questionId: "Q02", valor: 2 },
      ],
    },
    evidenceRefs: ["Q01", "Q02"],
    outputType: "brecha",
    severity: "alta",
    confidencePolicy: { base: 0.9, penalizacionInconsistencia: 0.35 },
    messageKey: "EST.direccion.ausente",
    priorityFactors: { impacto: 5, urgencia: 4, fundacionalidad: 5, factibilidad: 4 },
  },
  {
    ruleId: "RK-EST-002",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D01", capacidadId: "CAP-D01-02" },
    conditions: { tipo: "respuestaMenorIgual", questionId: "Q03", valor: 2 },
    evidenceRefs: ["Q03", "Q04"],
    outputType: "brecha",
    severity: "media",
    confidencePolicy: { base: 0.85, penalizacionInconsistencia: 0.3 },
    messageKey: "EST.gobierno.ausente",
    priorityFactors: { impacto: 4, urgencia: 3, fundacionalidad: 4, factibilidad: 5 },
    habilitadaPor: "CAP-D01-01",
  },
  {
    ruleId: "RK-EST-003",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D01", capacidadId: "CAP-D01-01" },
    conditions: {
      tipo: "todas",
      condiciones: [
        { tipo: "respuestaMayorIgual", questionId: "Q01", valor: 4 },
        { tipo: "respuestaMayorIgual", questionId: "Q02", valor: 4 },
      ],
    },
    evidenceRefs: ["Q01", "Q02"],
    outputType: "fortaleza",
    severity: "informativa",
    confidencePolicy: { base: 0.9, penalizacionInconsistencia: 0.35 },
    messageKey: "EST.direccion.solida",
    priorityFactors: { impacto: 2, urgencia: 1, fundacionalidad: 3, factibilidad: 5 },
  },
  {
    ruleId: "RK-EST-004",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D01", capacidadId: "CAP-D01-02" },
    conditions: { tipo: "senal", questionId: "Q04", senales: ["oportunidad"] },
    evidenceRefs: ["Q04"],
    outputType: "oportunidad",
    severity: "baja",
    confidencePolicy: { base: 0.75, penalizacionInconsistencia: 0.3 },
    messageKey: "EST.seguimiento.parcial",
    priorityFactors: { impacto: 3, urgencia: 2, fundacionalidad: 3, factibilidad: 5 },
  },

  /* ---------------- D02 · Clientes y canales ---------------- */
  {
    ruleId: "RK-CLI-001",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D02", capacidadId: "CAP-D02-01" },
    conditions: { tipo: "respuestaMenorIgual", questionId: "Q05", valor: 2 },
    evidenceRefs: ["Q05"],
    outputType: "brecha",
    severity: "media",
    confidencePolicy: { base: 0.85, penalizacionInconsistencia: 0.3 },
    messageKey: "CLI.clientes.sinUso",
    priorityFactors: { impacto: 4, urgencia: 3, fundacionalidad: 3, factibilidad: 4 },
  },
  {
    ruleId: "RK-CLI-002",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D02", capacidadId: "CAP-D02-02" },
    // Solo aplica si la pyme declara operar algún canal digital (CF-MC-10).
    applicability: { tipo: "canalDigital", presente: true },
    conditions: {
      tipo: "alguna",
      condiciones: [
        { tipo: "respuestaMenorIgual", questionId: "Q06", valor: 2 },
        { tipo: "respuestaMenorIgual", questionId: "Q07", valor: 2 },
      ],
    },
    evidenceRefs: ["Q06", "Q07"],
    outputType: "brecha",
    severity: "alta",
    confidencePolicy: { base: 0.85, penalizacionInconsistencia: 0.3 },
    messageKey: "CLI.canales.debiles",
    priorityFactors: { impacto: 5, urgencia: 4, fundacionalidad: 3, factibilidad: 4 },
  },
  {
    ruleId: "RK-CLI-003",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D02", capacidadId: "CAP-D02-02" },
    conditions: {
      tipo: "todas",
      condiciones: [
        { tipo: "respuestaMayorIgual", questionId: "Q06", valor: 4 },
        { tipo: "respuestaMayorIgual", questionId: "Q07", valor: 4 },
      ],
    },
    evidenceRefs: ["Q06", "Q07"],
    outputType: "fortaleza",
    severity: "informativa",
    confidencePolicy: { base: 0.9, penalizacionInconsistencia: 0.35 },
    messageKey: "CLI.canales.solidos",
    priorityFactors: { impacto: 2, urgencia: 1, fundacionalidad: 2, factibilidad: 5 },
  },
  {
    ruleId: "RK-CLI-004",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D02", capacidadId: "CAP-D02-01" },
    conditions: {
      tipo: "todas",
      condiciones: [
        { tipo: "respuestaMayorIgual", questionId: "Q05", valor: 4 },
        { tipo: "respuestaMenorIgual", questionId: "Q08", valor: 2 },
      ],
    },
    evidenceRefs: ["Q05", "Q08"],
    outputType: "oportunidad",
    severity: "media",
    confidencePolicy: { base: 0.8, penalizacionInconsistencia: 0.3 },
    messageKey: "CLI.medicion.oportunidad",
    priorityFactors: { impacto: 4, urgencia: 3, fundacionalidad: 2, factibilidad: 4 },
  },
  {
    // Segunda regla sobre la misma capacidad: la síntesis debe agrupar la evidencia
    // en un único hallazgo de fortaleza (CF-MC-05).
    ruleId: "RK-CLI-005",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D02", capacidadId: "CAP-D02-02" },
    conditions: { tipo: "respuestaMayorIgual", questionId: "Q06", valor: 5 },
    evidenceRefs: ["Q06"],
    outputType: "fortaleza",
    severity: "informativa",
    confidencePolicy: { base: 0.9 },
    messageKey: "CLI.canales.solidos",
    priorityFactors: { impacto: 2, urgencia: 1, fundacionalidad: 2, factibilidad: 5 },
  },

  /* ---------------- D03 · Procesos y operaciones ---------------- */
  {
    ruleId: "RK-PRO-001",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D03", capacidadId: "CAP-D03-01" },
    conditions: {
      tipo: "alguna",
      condiciones: [
        { tipo: "respuestaMenorIgual", questionId: "Q09", valor: 2 },
        { tipo: "respuestaMenorIgual", questionId: "Q11", valor: 2 },
      ],
    },
    evidenceRefs: ["Q09", "Q11"],
    outputType: "brecha",
    severity: "alta",
    confidencePolicy: { base: 0.85, penalizacionInconsistencia: 0.3 },
    messageKey: "PRO.procesos.informales",
    priorityFactors: { impacto: 4, urgencia: 3, fundacionalidad: 4, factibilidad: 3 },
  },
  {
    ruleId: "RK-PRO-002",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D03", capacidadId: "CAP-D03-02" },
    conditions: { tipo: "respuestaMenorIgual", questionId: "Q10", valor: 2 },
    evidenceRefs: ["Q10", "Q12"],
    outputType: "oportunidad",
    severity: "media",
    confidencePolicy: { base: 0.8, penalizacionInconsistencia: 0.3 },
    messageKey: "PRO.automatizacion.oportunidad",
    priorityFactors: { impacto: 3, urgencia: 2, fundacionalidad: 2, factibilidad: 3 },
    habilitadaPor: "CAP-D03-01",
  },
  {
    ruleId: "RK-PRO-003",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D03", capacidadId: "CAP-D03-01" },
    conditions: {
      tipo: "todas",
      condiciones: [
        { tipo: "respuestaMayorIgual", questionId: "Q09", valor: 4 },
        { tipo: "respuestaMayorIgual", questionId: "Q11", valor: 4 },
      ],
    },
    evidenceRefs: ["Q09", "Q11"],
    outputType: "fortaleza",
    severity: "informativa",
    confidencePolicy: { base: 0.9 },
    messageKey: "PRO.procesos.solidos",
    priorityFactors: { impacto: 2, urgencia: 1, fundacionalidad: 3, factibilidad: 5 },
  },

  /* ---------------- D04 · Tecnología y datos ---------------- */
  {
    ruleId: "RK-DAT-001",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D04", capacidadId: "CAP-D04-02" },
    conditions: { tipo: "respuestaMenorIgual", questionId: "Q16", valor: 2 },
    evidenceRefs: ["Q16"],
    outputType: "brecha",
    severity: "alta",
    confidencePolicy: { base: 0.85, penalizacionInconsistencia: 0.35 },
    messageKey: "DAT.decisiones.sinEvidencia",
    priorityFactors: { impacto: 5, urgencia: 3, fundacionalidad: 3, factibilidad: 3 },
    habilitadaPor: "CAP-D04-01",
  },
  {
    ruleId: "RK-DAT-002",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D04", capacidadId: "CAP-D04-01" },
    conditions: {
      tipo: "alguna",
      condiciones: [
        { tipo: "respuestaMenorIgual", questionId: "Q14", valor: 2 },
        { tipo: "respuestaMenorIgual", questionId: "Q15", valor: 2 },
      ],
    },
    evidenceRefs: ["Q14", "Q15"],
    outputType: "brecha",
    severity: "alta",
    confidencePolicy: { base: 0.85, penalizacionInconsistencia: 0.3 },
    messageKey: "DAT.informacion.dispersa",
    priorityFactors: { impacto: 4, urgencia: 3, fundacionalidad: 5, factibilidad: 3 },
  },
  {
    ruleId: "RK-DAT-003",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D04", capacidadId: "CAP-D04-02" },
    conditions: { tipo: "respuestaMayorIgual", questionId: "Q16", valor: 4 },
    evidenceRefs: ["Q16"],
    outputType: "fortaleza",
    severity: "informativa",
    confidencePolicy: { base: 0.9, penalizacionInconsistencia: 0.4 },
    messageKey: "DAT.decisiones.solidas",
    priorityFactors: { impacto: 2, urgencia: 1, fundacionalidad: 3, factibilidad: 5 },
  },
  {
    ruleId: "RK-DAT-004",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D04", capacidadId: "CAP-D04-01" },
    conditions: {
      tipo: "todas",
      condiciones: [
        { tipo: "respuestaMenorIgual", questionId: "Q14", valor: 2 },
        { tipo: "respuestaMenorIgual", questionId: "Q16", valor: 2 },
      ],
    },
    evidenceRefs: ["Q14", "Q16"],
    outputType: "dependencia",
    severity: "media",
    confidencePolicy: { base: 0.8 },
    messageKey: "DAT.dependencia.ordenAntesDeIndicadores",
    priorityFactors: { impacto: 4, urgencia: 3, fundacionalidad: 5, factibilidad: 3 },
  },
  {
    ruleId: "RK-DAT-005",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D04", capacidadId: "CAP-D04-01" },
    conditions: {
      tipo: "todas",
      condiciones: [
        { tipo: "respuestaMayorIgual", questionId: "Q13", valor: 4 },
        { tipo: "respuestaMayorIgual", questionId: "Q14", valor: 4 },
      ],
    },
    evidenceRefs: ["Q13", "Q14"],
    outputType: "fortaleza",
    severity: "informativa",
    confidencePolicy: { base: 0.9 },
    messageKey: "DAT.informacion.parcial",
    priorityFactors: { impacto: 2, urgencia: 1, fundacionalidad: 3, factibilidad: 5 },
  },

  /* ---------------- D05 · Personas y cultura ---------------- */
  {
    ruleId: "RK-TAL-001",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D05", capacidadId: "CAP-D05-01" },
    conditions: {
      tipo: "alguna",
      condiciones: [
        { tipo: "respuestaMenorIgual", questionId: "Q17", valor: 2 },
        { tipo: "respuestaMenorIgual", questionId: "Q18", valor: 2 },
      ],
    },
    evidenceRefs: ["Q17", "Q18"],
    outputType: "brecha",
    severity: "media",
    confidencePolicy: { base: 0.85, penalizacionInconsistencia: 0.3 },
    messageKey: "TAL.competencias.insuficientes",
    priorityFactors: { impacto: 4, urgencia: 3, fundacionalidad: 4, factibilidad: 3 },
  },
  {
    ruleId: "RK-TAL-002",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D05", capacidadId: "CAP-D05-02" },
    conditions: {
      tipo: "todas",
      condiciones: [
        { tipo: "respuestaMayorIgual", questionId: "Q19", valor: 4 },
        { tipo: "respuestaMayorIgual", questionId: "Q20", valor: 4 },
      ],
    },
    evidenceRefs: ["Q19", "Q20"],
    outputType: "fortaleza",
    severity: "informativa",
    confidencePolicy: { base: 0.9 },
    messageKey: "TAL.cultura.solida",
    priorityFactors: { impacto: 2, urgencia: 1, fundacionalidad: 3, factibilidad: 5 },
  },
  {
    ruleId: "RK-TAL-003",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D05", capacidadId: "CAP-D05-01" },
    conditions: {
      tipo: "todas",
      condiciones: [
        { tipo: "respuestaMayorIgual", questionId: "Q20", valor: 4 },
        { tipo: "respuestaMenorIgual", questionId: "Q17", valor: 3 },
      ],
    },
    evidenceRefs: ["Q17", "Q20"],
    outputType: "oportunidad",
    severity: "baja",
    confidencePolicy: { base: 0.8 },
    messageKey: "TAL.disposicion.sinCompetencias",
    priorityFactors: { impacto: 3, urgencia: 2, fundacionalidad: 3, factibilidad: 4 },
  },

  /* ---------------- D06 · Seguridad y continuidad ---------------- */
  {
    // Regla histórica conservada como trazabilidad de versión (POC-04, 8 y CF-MC-08).
    ruleId: "RK-SEG-000",
    version: "0.9.0",
    status: "deprecated",
    scope: { dimensionId: "D06", capacidadId: "CAP-D06-01" },
    conditions: { tipo: "respuestaMenorIgual", questionId: "Q21", valor: 3 },
    evidenceRefs: ["Q21"],
    outputType: "riesgo",
    severity: "media",
    confidencePolicy: { base: 0.7 },
    messageKey: "SEG.accesos.sinControl",
    priorityFactors: { impacto: 4, urgencia: 3, fundacionalidad: 4, factibilidad: 4 },
  },
  {
    ruleId: "RK-SEG-001",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D06", capacidadId: "CAP-D06-01" },
    conditions: { tipo: "respuestaMenorIgual", questionId: "Q21", valor: 2 },
    evidenceRefs: ["Q21"],
    outputType: "riesgo",
    severity: "critica",
    confidencePolicy: { base: 0.9, penalizacionInconsistencia: 0.25 },
    messageKey: "SEG.accesos.sinControl",
    priorityFactors: { impacto: 5, urgencia: 5, fundacionalidad: 5, factibilidad: 4 },
    escalaCritica: true,
    supersedes: "RK-SEG-000",
  },
  {
    ruleId: "RK-SEG-002",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D06", capacidadId: "CAP-D06-01" },
    conditions: { tipo: "respuestaMenorIgual", questionId: "Q22", valor: 2 },
    evidenceRefs: ["Q22"],
    outputType: "riesgo",
    severity: "critica",
    confidencePolicy: { base: 0.9, penalizacionInconsistencia: 0.25 },
    messageKey: "SEG.respaldo.ausente",
    priorityFactors: { impacto: 5, urgencia: 5, fundacionalidad: 4, factibilidad: 5 },
    escalaCritica: true,
  },
  {
    ruleId: "RK-SEG-003",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D06", capacidadId: "CAP-D06-02" },
    conditions: { tipo: "respuestaMenorIgual", questionId: "Q23", valor: 2 },
    evidenceRefs: ["Q23"],
    outputType: "riesgo",
    severity: "alta",
    confidencePolicy: { base: 0.85, penalizacionInconsistencia: 0.3 },
    messageKey: "SEG.practicas.debiles",
    priorityFactors: { impacto: 4, urgencia: 4, fundacionalidad: 3, factibilidad: 5 },
  },
  {
    ruleId: "RK-SEG-004",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D06", capacidadId: "CAP-D06-02" },
    conditions: { tipo: "respuestaMenorIgual", questionId: "Q24", valor: 2 },
    evidenceRefs: ["Q24"],
    outputType: "brecha",
    severity: "alta",
    confidencePolicy: { base: 0.85, penalizacionInconsistencia: 0.3 },
    messageKey: "SEG.continuidad.ausente",
    priorityFactors: { impacto: 4, urgencia: 4, fundacionalidad: 3, factibilidad: 3 },
    habilitadaPor: "CAP-D06-01",
  },
  {
    ruleId: "RK-SEG-005",
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: "D06", capacidadId: "CAP-D06-01" },
    conditions: {
      tipo: "todas",
      condiciones: [
        { tipo: "respuestaMayorIgual", questionId: "Q21", valor: 4 },
        { tipo: "respuestaMayorIgual", questionId: "Q22", valor: 4 },
      ],
    },
    evidenceRefs: ["Q21", "Q22"],
    outputType: "fortaleza",
    severity: "informativa",
    confidencePolicy: { base: 0.9 },
    messageKey: "SEG.base.solida",
    priorityFactors: { impacto: 2, urgencia: 1, fundacionalidad: 3, factibilidad: 5 },
  },

  /* ---------------- Consistencia ---------------- */
  ...["INC-01", "INC-02", "INC-03", "INC-04"].map<Regla>((parId, indice) => ({
    ruleId: `RK-CONS-00${indice + 1}`,
    version: "1.0.0",
    status: "active",
    scope: { dimensionId: ["D04", "D03", "D06", "D01"][indice]!, capacidadId: null },
    conditions: { tipo: "inconsistencia", parId },
    evidenceRefs: [],
    outputType: "inconsistencia",
    severity: "baja",
    confidencePolicy: { base: 0.6 },
    messageKey: "CONS.contradiccion",
    priorityFactors: { impacto: 2, urgencia: 2, fundacionalidad: 1, factibilidad: 5 },
  })),
];

export const reglasActivas = reglas.filter((r) => r.status === "active");

export function obtenerRegla(ruleId: string): Regla | undefined {
  return reglas.find((r) => r.ruleId === ruleId);
}
