/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AccesoRouteImport } from './routes/acceso'
import { Route as ApoyoRouteImport } from './routes/apoyo'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as CohorteRouteImport } from './routes/cohorte'
import { Route as ColaboracionRouteImport } from './routes/colaboracion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemostracionRouteImport } from './routes/demostracion'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as ModaOrigenRouteImport } from './routes/moda-origen'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanDeAccionRouteImport } from './routes/plan-de-accion'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as SeguimientoRouteImport } from './routes/seguimiento'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAlertasRouteImport } from './routes/dashboard.alertas'
import { Route as DiagnosticoIndexRouteImport } from './routes/diagnostico.index'
import { Route as DiagnosticoCierreRouteImport } from './routes/diagnostico.cierre'
import { Route as DiagnosticoEspecializadosRouteImport } from './routes/diagnostico.especializados'
import { Route as DiagnosticoListoRouteImport } from './routes/diagnostico.listo'
import { Route as DiagnosticoMotorRouteImport } from './routes/diagnostico.motor'
import { Route as DiagnosticoProcesandoRouteImport } from './routes/diagnostico.procesando'
import { Route as DiagnosticoResumenRouteImport } from './routes/diagnostico.resumen'
import { Route as DiagnosticoRevisionRouteImport } from './routes/diagnostico.revision'
import { Route as PlanDeAccionIndexRouteImport } from './routes/plan-de-accion.index'
import { Route as PlanDeAccionAccionRouteImport } from './routes/plan-de-accion.$accion'
import { Route as PlanDeAccionCierreRouteImport } from './routes/plan-de-accion.cierre'
import { Route as PlanDeAccionEntradaRouteImport } from './routes/plan-de-accion.entrada'
import { Route as ProyectoActividadRouteImport } from './routes/proyecto.$actividad'
import { Route as ResultadosIndexRouteImport } from './routes/resultados.index'
import { Route as ResultadosDimensionRouteImport } from './routes/resultados.$dimension'
import { Route as RoadmapIndexRouteImport } from './routes/roadmap.index'
import { Route as RoadmapAccionRouteImport } from './routes/roadmap.$accion'
import { Route as SeguimientoIndexRouteImport } from './routes/seguimiento.index'
import { Route as SeguimientoActividadRouteImport } from './routes/seguimiento.$actividad'
import { Route as SeguimientoEntradaRouteImport } from './routes/seguimiento.entrada'
import { Route as AuthenticatedCapacidadOp01RouteImport } from './routes/_authenticated/capacidad.op-01'
import { Route as DashboardDimensionDimensionRouteImport } from './routes/dashboard.dimension.$dimension'
import { Route as DiagnosticoEspecializadosIndexRouteImport } from './routes/diagnostico.especializados.index'
import { Route as DiagnosticoEspecializadosEcommerceRouteImport } from './routes/diagnostico.especializados.ecommerce'
import { Route as DiagnosticoPasoIdRouteImport } from './routes/diagnostico.paso.$id'
import { Route as PlanDeAccionWorkspaceActividadRouteImport } from './routes/plan-de-accion.workspace.$actividad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoRoute = AccesoRouteImport.update({
  id: '/acceso',
  path: '/acceso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoyoRoute = ApoyoRouteImport.update({
  id: '/apoyo',
  path: '/apoyo',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const CohorteRoute = CohorteRouteImport.update({
  id: '/cohorte',
  path: '/cohorte',
  getParentRoute: () => rootRouteImport,
} as any)
const ColaboracionRoute = ColaboracionRouteImport.update({
  id: '/colaboracion',
  path: '/colaboracion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemostracionRoute = DemostracionRouteImport.update({
  id: '/demostracion',
  path: '/demostracion',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const ModaOrigenRoute = ModaOrigenRouteImport.update({
  id: '/moda-origen',
  path: '/moda-origen',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanDeAccionRoute = PlanDeAccionRouteImport.update({
  id: '/plan-de-accion',
  path: '/plan-de-accion',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguimientoRoute = SeguimientoRouteImport.update({
  id: '/seguimiento',
  path: '/seguimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertasRoute = DashboardAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => DashboardRoute,
} as any)
const DiagnosticoIndexRoute = DiagnosticoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const DiagnosticoCierreRoute = DiagnosticoCierreRouteImport.update({
  id: '/cierre',
  path: '/cierre',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const DiagnosticoEspecializadosRoute =
  DiagnosticoEspecializadosRouteImport.update({
    id: '/especializados',
    path: '/especializados',
    getParentRoute: () => DiagnosticoRoute,
  } as any)
const DiagnosticoListoRoute = DiagnosticoListoRouteImport.update({
  id: '/listo',
  path: '/listo',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const DiagnosticoMotorRoute = DiagnosticoMotorRouteImport.update({
  id: '/motor',
  path: '/motor',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const DiagnosticoProcesandoRoute = DiagnosticoProcesandoRouteImport.update({
  id: '/procesando',
  path: '/procesando',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const DiagnosticoResumenRoute = DiagnosticoResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const DiagnosticoRevisionRoute = DiagnosticoRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const PlanDeAccionIndexRoute = PlanDeAccionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlanDeAccionRoute,
} as any)
const PlanDeAccionAccionRoute = PlanDeAccionAccionRouteImport.update({
  id: '/$accion',
  path: '/$accion',
  getParentRoute: () => PlanDeAccionRoute,
} as any)
const PlanDeAccionCierreRoute = PlanDeAccionCierreRouteImport.update({
  id: '/cierre',
  path: '/cierre',
  getParentRoute: () => PlanDeAccionRoute,
} as any)
const PlanDeAccionEntradaRoute = PlanDeAccionEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => PlanDeAccionRoute,
} as any)
const ProyectoActividadRoute = ProyectoActividadRouteImport.update({
  id: '/proyecto/$actividad',
  path: '/proyecto/$actividad',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosIndexRoute = ResultadosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResultadosRoute,
} as any)
const ResultadosDimensionRoute = ResultadosDimensionRouteImport.update({
  id: '/$dimension',
  path: '/$dimension',
  getParentRoute: () => ResultadosRoute,
} as any)
const RoadmapIndexRoute = RoadmapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoadmapRoute,
} as any)
const RoadmapAccionRoute = RoadmapAccionRouteImport.update({
  id: '/$accion',
  path: '/$accion',
  getParentRoute: () => RoadmapRoute,
} as any)
const SeguimientoIndexRoute = SeguimientoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SeguimientoRoute,
} as any)
const SeguimientoActividadRoute = SeguimientoActividadRouteImport.update({
  id: '/$actividad',
  path: '/$actividad',
  getParentRoute: () => SeguimientoRoute,
} as any)
const SeguimientoEntradaRoute = SeguimientoEntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => SeguimientoRoute,
} as any)
const AuthenticatedCapacidadOp01Route =
  AuthenticatedCapacidadOp01RouteImport.update({
    id: '/capacidad/op-01',
    path: '/capacidad/op-01',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DashboardDimensionDimensionRoute =
  DashboardDimensionDimensionRouteImport.update({
    id: '/dimension/$dimension',
    path: '/dimension/$dimension',
    getParentRoute: () => DashboardRoute,
  } as any)
const DiagnosticoEspecializadosIndexRoute =
  DiagnosticoEspecializadosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DiagnosticoEspecializadosRoute,
  } as any)
const DiagnosticoEspecializadosEcommerceRoute =
  DiagnosticoEspecializadosEcommerceRouteImport.update({
    id: '/ecommerce',
    path: '/ecommerce',
    getParentRoute: () => DiagnosticoEspecializadosRoute,
  } as any)
const DiagnosticoPasoIdRoute = DiagnosticoPasoIdRouteImport.update({
  id: '/paso/$id',
  path: '/paso/$id',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const PlanDeAccionWorkspaceActividadRoute =
  PlanDeAccionWorkspaceActividadRouteImport.update({
    id: '/workspace/$actividad',
    path: '/workspace/$actividad',
    getParentRoute: () => PlanDeAccionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/apoyo': typeof ApoyoRoute
  '/ayuda': typeof AyudaRoute
  '/cohorte': typeof CohorteRoute
  '/colaboracion': typeof ColaboracionRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demostracion': typeof DemostracionRoute
  '/diagnostico': typeof DiagnosticoRouteWithChildren
  '/inicio': typeof InicioRoute
  '/moda-origen': typeof ModaOrigenRoute
  '/perfil': typeof PerfilRoute
  '/plan-de-accion': typeof PlanDeAccionRouteWithChildren
  '/resultados': typeof ResultadosRouteWithChildren
  '/roadmap': typeof RoadmapRouteWithChildren
  '/seguimiento': typeof SeguimientoRouteWithChildren
  '/dashboard/alertas': typeof DashboardAlertasRoute
  '/diagnostico/cierre': typeof DiagnosticoCierreRoute
  '/diagnostico/especializados': typeof DiagnosticoEspecializadosRouteWithChildren
  '/diagnostico/listo': typeof DiagnosticoListoRoute
  '/diagnostico/motor': typeof DiagnosticoMotorRoute
  '/diagnostico/procesando': typeof DiagnosticoProcesandoRoute
  '/diagnostico/resumen': typeof DiagnosticoResumenRoute
  '/diagnostico/revision': typeof DiagnosticoRevisionRoute
  '/plan-de-accion/$accion': typeof PlanDeAccionAccionRoute
  '/plan-de-accion/cierre': typeof PlanDeAccionCierreRoute
  '/plan-de-accion/entrada': typeof PlanDeAccionEntradaRoute
  '/proyecto/$actividad': typeof ProyectoActividadRoute
  '/resultados/$dimension': typeof ResultadosDimensionRoute
  '/roadmap/$accion': typeof RoadmapAccionRoute
  '/seguimiento/$actividad': typeof SeguimientoActividadRoute
  '/seguimiento/entrada': typeof SeguimientoEntradaRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/diagnostico/': typeof DiagnosticoIndexRoute
  '/plan-de-accion/': typeof PlanDeAccionIndexRoute
  '/resultados/': typeof ResultadosIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/seguimiento/': typeof SeguimientoIndexRoute
  '/capacidad/op-01': typeof AuthenticatedCapacidadOp01Route
  '/dashboard/dimension/$dimension': typeof DashboardDimensionDimensionRoute
  '/diagnostico/especializados/ecommerce': typeof DiagnosticoEspecializadosEcommerceRoute
  '/diagnostico/paso/$id': typeof DiagnosticoPasoIdRoute
  '/plan-de-accion/workspace/$actividad': typeof PlanDeAccionWorkspaceActividadRoute
  '/diagnostico/especializados/': typeof DiagnosticoEspecializadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acceso': typeof AccesoRoute
  '/apoyo': typeof ApoyoRoute
  '/ayuda': typeof AyudaRoute
  '/cohorte': typeof CohorteRoute
  '/colaboracion': typeof ColaboracionRoute
  '/demostracion': typeof DemostracionRoute
  '/inicio': typeof InicioRoute
  '/moda-origen': typeof ModaOrigenRoute
  '/perfil': typeof PerfilRoute
  '/dashboard/alertas': typeof DashboardAlertasRoute
  '/diagnostico/cierre': typeof DiagnosticoCierreRoute
  '/diagnostico/listo': typeof DiagnosticoListoRoute
  '/diagnostico/motor': typeof DiagnosticoMotorRoute
  '/diagnostico/procesando': typeof DiagnosticoProcesandoRoute
  '/diagnostico/resumen': typeof DiagnosticoResumenRoute
  '/diagnostico/revision': typeof DiagnosticoRevisionRoute
  '/plan-de-accion/$accion': typeof PlanDeAccionAccionRoute
  '/plan-de-accion/cierre': typeof PlanDeAccionCierreRoute
  '/plan-de-accion/entrada': typeof PlanDeAccionEntradaRoute
  '/proyecto/$actividad': typeof ProyectoActividadRoute
  '/resultados/$dimension': typeof ResultadosDimensionRoute
  '/roadmap/$accion': typeof RoadmapAccionRoute
  '/seguimiento/$actividad': typeof SeguimientoActividadRoute
  '/seguimiento/entrada': typeof SeguimientoEntradaRoute
  '/dashboard': typeof DashboardIndexRoute
  '/diagnostico': typeof DiagnosticoIndexRoute
  '/plan-de-accion': typeof PlanDeAccionIndexRoute
  '/resultados': typeof ResultadosIndexRoute
  '/roadmap': typeof RoadmapIndexRoute
  '/seguimiento': typeof SeguimientoIndexRoute
  '/capacidad/op-01': typeof AuthenticatedCapacidadOp01Route
  '/dashboard/dimension/$dimension': typeof DashboardDimensionDimensionRoute
  '/diagnostico/especializados/ecommerce': typeof DiagnosticoEspecializadosEcommerceRoute
  '/diagnostico/paso/$id': typeof DiagnosticoPasoIdRoute
  '/plan-de-accion/workspace/$actividad': typeof PlanDeAccionWorkspaceActividadRoute
  '/diagnostico/especializados': typeof DiagnosticoEspecializadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acceso': typeof AccesoRoute
  '/apoyo': typeof ApoyoRoute
  '/ayuda': typeof AyudaRoute
  '/cohorte': typeof CohorteRoute
  '/colaboracion': typeof ColaboracionRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demostracion': typeof DemostracionRoute
  '/diagnostico': typeof DiagnosticoRouteWithChildren
  '/inicio': typeof InicioRoute
  '/moda-origen': typeof ModaOrigenRoute
  '/perfil': typeof PerfilRoute
  '/plan-de-accion': typeof PlanDeAccionRouteWithChildren
  '/resultados': typeof ResultadosRouteWithChildren
  '/roadmap': typeof RoadmapRouteWithChildren
  '/seguimiento': typeof SeguimientoRouteWithChildren
  '/dashboard/alertas': typeof DashboardAlertasRoute
  '/diagnostico/cierre': typeof DiagnosticoCierreRoute
  '/diagnostico/especializados': typeof DiagnosticoEspecializadosRouteWithChildren
  '/diagnostico/listo': typeof DiagnosticoListoRoute
  '/diagnostico/motor': typeof DiagnosticoMotorRoute
  '/diagnostico/procesando': typeof DiagnosticoProcesandoRoute
  '/diagnostico/resumen': typeof DiagnosticoResumenRoute
  '/diagnostico/revision': typeof DiagnosticoRevisionRoute
  '/plan-de-accion/$accion': typeof PlanDeAccionAccionRoute
  '/plan-de-accion/cierre': typeof PlanDeAccionCierreRoute
  '/plan-de-accion/entrada': typeof PlanDeAccionEntradaRoute
  '/proyecto/$actividad': typeof ProyectoActividadRoute
  '/resultados/$dimension': typeof ResultadosDimensionRoute
  '/roadmap/$accion': typeof RoadmapAccionRoute
  '/seguimiento/$actividad': typeof SeguimientoActividadRoute
  '/seguimiento/entrada': typeof SeguimientoEntradaRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/diagnostico/': typeof DiagnosticoIndexRoute
  '/plan-de-accion/': typeof PlanDeAccionIndexRoute
  '/resultados/': typeof ResultadosIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/seguimiento/': typeof SeguimientoIndexRoute
  '/_authenticated/capacidad/op-01': typeof AuthenticatedCapacidadOp01Route
  '/dashboard/dimension/$dimension': typeof DashboardDimensionDimensionRoute
  '/diagnostico/especializados/ecommerce': typeof DiagnosticoEspecializadosEcommerceRoute
  '/diagnostico/paso/$id': typeof DiagnosticoPasoIdRoute
  '/plan-de-accion/workspace/$actividad': typeof PlanDeAccionWorkspaceActividadRoute
  '/diagnostico/especializados/': typeof DiagnosticoEspecializadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acceso'
    | '/apoyo'
    | '/ayuda'
    | '/cohorte'
    | '/colaboracion'
    | '/dashboard'
    | '/demostracion'
    | '/diagnostico'
    | '/inicio'
    | '/moda-origen'
    | '/perfil'
    | '/plan-de-accion'
    | '/resultados'
    | '/roadmap'
    | '/seguimiento'
    | '/dashboard/alertas'
    | '/diagnostico/cierre'
    | '/diagnostico/especializados'
    | '/diagnostico/listo'
    | '/diagnostico/motor'
    | '/diagnostico/procesando'
    | '/diagnostico/resumen'
    | '/diagnostico/revision'
    | '/plan-de-accion/$accion'
    | '/plan-de-accion/cierre'
    | '/plan-de-accion/entrada'
    | '/proyecto/$actividad'
    | '/resultados/$dimension'
    | '/roadmap/$accion'
    | '/seguimiento/$actividad'
    | '/seguimiento/entrada'
    | '/dashboard/'
    | '/diagnostico/'
    | '/plan-de-accion/'
    | '/resultados/'
    | '/roadmap/'
    | '/seguimiento/'
    | '/capacidad/op-01'
    | '/dashboard/dimension/$dimension'
    | '/diagnostico/especializados/ecommerce'
    | '/diagnostico/paso/$id'
    | '/plan-de-accion/workspace/$actividad'
    | '/diagnostico/especializados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acceso'
    | '/apoyo'
    | '/ayuda'
    | '/cohorte'
    | '/colaboracion'
    | '/demostracion'
    | '/inicio'
    | '/moda-origen'
    | '/perfil'
    | '/dashboard/alertas'
    | '/diagnostico/cierre'
    | '/diagnostico/listo'
    | '/diagnostico/motor'
    | '/diagnostico/procesando'
    | '/diagnostico/resumen'
    | '/diagnostico/revision'
    | '/plan-de-accion/$accion'
    | '/plan-de-accion/cierre'
    | '/plan-de-accion/entrada'
    | '/proyecto/$actividad'
    | '/resultados/$dimension'
    | '/roadmap/$accion'
    | '/seguimiento/$actividad'
    | '/seguimiento/entrada'
    | '/dashboard'
    | '/diagnostico'
    | '/plan-de-accion'
    | '/resultados'
    | '/roadmap'
    | '/seguimiento'
    | '/capacidad/op-01'
    | '/dashboard/dimension/$dimension'
    | '/diagnostico/especializados/ecommerce'
    | '/diagnostico/paso/$id'
    | '/plan-de-accion/workspace/$actividad'
    | '/diagnostico/especializados'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acceso'
    | '/apoyo'
    | '/ayuda'
    | '/cohorte'
    | '/colaboracion'
    | '/dashboard'
    | '/demostracion'
    | '/diagnostico'
    | '/inicio'
    | '/moda-origen'
    | '/perfil'
    | '/plan-de-accion'
    | '/resultados'
    | '/roadmap'
    | '/seguimiento'
    | '/dashboard/alertas'
    | '/diagnostico/cierre'
    | '/diagnostico/especializados'
    | '/diagnostico/listo'
    | '/diagnostico/motor'
    | '/diagnostico/procesando'
    | '/diagnostico/resumen'
    | '/diagnostico/revision'
    | '/plan-de-accion/$accion'
    | '/plan-de-accion/cierre'
    | '/plan-de-accion/entrada'
    | '/proyecto/$actividad'
    | '/resultados/$dimension'
    | '/roadmap/$accion'
    | '/seguimiento/$actividad'
    | '/seguimiento/entrada'
    | '/dashboard/'
    | '/diagnostico/'
    | '/plan-de-accion/'
    | '/resultados/'
    | '/roadmap/'
    | '/seguimiento/'
    | '/_authenticated/capacidad/op-01'
    | '/dashboard/dimension/$dimension'
    | '/diagnostico/especializados/ecommerce'
    | '/diagnostico/paso/$id'
    | '/plan-de-accion/workspace/$actividad'
    | '/diagnostico/especializados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccesoRoute: typeof AccesoRoute
  ApoyoRoute: typeof ApoyoRoute
  AyudaRoute: typeof AyudaRoute
  CohorteRoute: typeof CohorteRoute
  ColaboracionRoute: typeof ColaboracionRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemostracionRoute: typeof DemostracionRoute
  DiagnosticoRoute: typeof DiagnosticoRouteWithChildren
  InicioRoute: typeof InicioRoute
  ModaOrigenRoute: typeof ModaOrigenRoute
  PerfilRoute: typeof PerfilRoute
  PlanDeAccionRoute: typeof PlanDeAccionRouteWithChildren
  ResultadosRoute: typeof ResultadosRouteWithChildren
  RoadmapRoute: typeof RoadmapRouteWithChildren
  SeguimientoRoute: typeof SeguimientoRouteWithChildren
  ProyectoActividadRoute: typeof ProyectoActividadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceso': {
      id: '/acceso'
      path: '/acceso'
      fullPath: '/acceso'
      preLoaderRoute: typeof AccesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoyo': {
      id: '/apoyo'
      path: '/apoyo'
      fullPath: '/apoyo'
      preLoaderRoute: typeof ApoyoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cohorte': {
      id: '/cohorte'
      path: '/cohorte'
      fullPath: '/cohorte'
      preLoaderRoute: typeof CohorteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colaboracion': {
      id: '/colaboracion'
      path: '/colaboracion'
      fullPath: '/colaboracion'
      preLoaderRoute: typeof ColaboracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demostracion': {
      id: '/demostracion'
      path: '/demostracion'
      fullPath: '/demostracion'
      preLoaderRoute: typeof DemostracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moda-origen': {
      id: '/moda-origen'
      path: '/moda-origen'
      fullPath: '/moda-origen'
      preLoaderRoute: typeof ModaOrigenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-de-accion': {
      id: '/plan-de-accion'
      path: '/plan-de-accion'
      fullPath: '/plan-de-accion'
      preLoaderRoute: typeof PlanDeAccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguimiento': {
      id: '/seguimiento'
      path: '/seguimiento'
      fullPath: '/seguimiento'
      preLoaderRoute: typeof SeguimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alertas': {
      id: '/dashboard/alertas'
      path: '/alertas'
      fullPath: '/dashboard/alertas'
      preLoaderRoute: typeof DashboardAlertasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/diagnostico/': {
      id: '/diagnostico/'
      path: '/'
      fullPath: '/diagnostico/'
      preLoaderRoute: typeof DiagnosticoIndexRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/cierre': {
      id: '/diagnostico/cierre'
      path: '/cierre'
      fullPath: '/diagnostico/cierre'
      preLoaderRoute: typeof DiagnosticoCierreRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/especializados': {
      id: '/diagnostico/especializados'
      path: '/especializados'
      fullPath: '/diagnostico/especializados'
      preLoaderRoute: typeof DiagnosticoEspecializadosRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/listo': {
      id: '/diagnostico/listo'
      path: '/listo'
      fullPath: '/diagnostico/listo'
      preLoaderRoute: typeof DiagnosticoListoRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/motor': {
      id: '/diagnostico/motor'
      path: '/motor'
      fullPath: '/diagnostico/motor'
      preLoaderRoute: typeof DiagnosticoMotorRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/procesando': {
      id: '/diagnostico/procesando'
      path: '/procesando'
      fullPath: '/diagnostico/procesando'
      preLoaderRoute: typeof DiagnosticoProcesandoRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/resumen': {
      id: '/diagnostico/resumen'
      path: '/resumen'
      fullPath: '/diagnostico/resumen'
      preLoaderRoute: typeof DiagnosticoResumenRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/revision': {
      id: '/diagnostico/revision'
      path: '/revision'
      fullPath: '/diagnostico/revision'
      preLoaderRoute: typeof DiagnosticoRevisionRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/plan-de-accion/': {
      id: '/plan-de-accion/'
      path: '/'
      fullPath: '/plan-de-accion/'
      preLoaderRoute: typeof PlanDeAccionIndexRouteImport
      parentRoute: typeof PlanDeAccionRoute
    }
    '/plan-de-accion/$accion': {
      id: '/plan-de-accion/$accion'
      path: '/$accion'
      fullPath: '/plan-de-accion/$accion'
      preLoaderRoute: typeof PlanDeAccionAccionRouteImport
      parentRoute: typeof PlanDeAccionRoute
    }
    '/plan-de-accion/cierre': {
      id: '/plan-de-accion/cierre'
      path: '/cierre'
      fullPath: '/plan-de-accion/cierre'
      preLoaderRoute: typeof PlanDeAccionCierreRouteImport
      parentRoute: typeof PlanDeAccionRoute
    }
    '/plan-de-accion/entrada': {
      id: '/plan-de-accion/entrada'
      path: '/entrada'
      fullPath: '/plan-de-accion/entrada'
      preLoaderRoute: typeof PlanDeAccionEntradaRouteImport
      parentRoute: typeof PlanDeAccionRoute
    }
    '/proyecto/$actividad': {
      id: '/proyecto/$actividad'
      path: '/proyecto/$actividad'
      fullPath: '/proyecto/$actividad'
      preLoaderRoute: typeof ProyectoActividadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados/': {
      id: '/resultados/'
      path: '/'
      fullPath: '/resultados/'
      preLoaderRoute: typeof ResultadosIndexRouteImport
      parentRoute: typeof ResultadosRoute
    }
    '/resultados/$dimension': {
      id: '/resultados/$dimension'
      path: '/$dimension'
      fullPath: '/resultados/$dimension'
      preLoaderRoute: typeof ResultadosDimensionRouteImport
      parentRoute: typeof ResultadosRoute
    }
    '/roadmap/': {
      id: '/roadmap/'
      path: '/'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof RoadmapIndexRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/roadmap/$accion': {
      id: '/roadmap/$accion'
      path: '/$accion'
      fullPath: '/roadmap/$accion'
      preLoaderRoute: typeof RoadmapAccionRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/seguimiento/': {
      id: '/seguimiento/'
      path: '/'
      fullPath: '/seguimiento/'
      preLoaderRoute: typeof SeguimientoIndexRouteImport
      parentRoute: typeof SeguimientoRoute
    }
    '/seguimiento/$actividad': {
      id: '/seguimiento/$actividad'
      path: '/$actividad'
      fullPath: '/seguimiento/$actividad'
      preLoaderRoute: typeof SeguimientoActividadRouteImport
      parentRoute: typeof SeguimientoRoute
    }
    '/seguimiento/entrada': {
      id: '/seguimiento/entrada'
      path: '/entrada'
      fullPath: '/seguimiento/entrada'
      preLoaderRoute: typeof SeguimientoEntradaRouteImport
      parentRoute: typeof SeguimientoRoute
    }
    '/_authenticated/capacidad/op-01': {
      id: '/_authenticated/capacidad/op-01'
      path: '/capacidad/op-01'
      fullPath: '/capacidad/op-01'
      preLoaderRoute: typeof AuthenticatedCapacidadOp01RouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/dashboard/dimension/$dimension': {
      id: '/dashboard/dimension/$dimension'
      path: '/dimension/$dimension'
      fullPath: '/dashboard/dimension/$dimension'
      preLoaderRoute: typeof DashboardDimensionDimensionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/diagnostico/especializados/': {
      id: '/diagnostico/especializados/'
      path: '/'
      fullPath: '/diagnostico/especializados/'
      preLoaderRoute: typeof DiagnosticoEspecializadosIndexRouteImport
      parentRoute: typeof DiagnosticoEspecializadosRoute
    }
    '/diagnostico/especializados/ecommerce': {
      id: '/diagnostico/especializados/ecommerce'
      path: '/ecommerce'
      fullPath: '/diagnostico/especializados/ecommerce'
      preLoaderRoute: typeof DiagnosticoEspecializadosEcommerceRouteImport
      parentRoute: typeof DiagnosticoEspecializadosRoute
    }
    '/diagnostico/paso/$id': {
      id: '/diagnostico/paso/$id'
      path: '/paso/$id'
      fullPath: '/diagnostico/paso/$id'
      preLoaderRoute: typeof DiagnosticoPasoIdRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/plan-de-accion/workspace/$actividad': {
      id: '/plan-de-accion/workspace/$actividad'
      path: '/workspace/$actividad'
      fullPath: '/plan-de-accion/workspace/$actividad'
      preLoaderRoute: typeof PlanDeAccionWorkspaceActividadRouteImport
      parentRoute: typeof PlanDeAccionRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCapacidadOp01Route: typeof AuthenticatedCapacidadOp01Route
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCapacidadOp01Route: AuthenticatedCapacidadOp01Route,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DashboardRouteChildren {
  DashboardAlertasRoute: typeof DashboardAlertasRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDimensionDimensionRoute: typeof DashboardDimensionDimensionRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertasRoute: DashboardAlertasRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDimensionDimensionRoute: DashboardDimensionDimensionRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DiagnosticoEspecializadosRouteChildren {
  DiagnosticoEspecializadosEcommerceRoute: typeof DiagnosticoEspecializadosEcommerceRoute
  DiagnosticoEspecializadosIndexRoute: typeof DiagnosticoEspecializadosIndexRoute
}

const DiagnosticoEspecializadosRouteChildren: DiagnosticoEspecializadosRouteChildren =
  {
    DiagnosticoEspecializadosEcommerceRoute:
      DiagnosticoEspecializadosEcommerceRoute,
    DiagnosticoEspecializadosIndexRoute: DiagnosticoEspecializadosIndexRoute,
  }

const DiagnosticoEspecializadosRouteWithChildren =
  DiagnosticoEspecializadosRoute._addFileChildren(
    DiagnosticoEspecializadosRouteChildren,
  )

interface DiagnosticoRouteChildren {
  DiagnosticoCierreRoute: typeof DiagnosticoCierreRoute
  DiagnosticoEspecializadosRoute: typeof DiagnosticoEspecializadosRouteWithChildren
  DiagnosticoListoRoute: typeof DiagnosticoListoRoute
  DiagnosticoMotorRoute: typeof DiagnosticoMotorRoute
  DiagnosticoProcesandoRoute: typeof DiagnosticoProcesandoRoute
  DiagnosticoResumenRoute: typeof DiagnosticoResumenRoute
  DiagnosticoRevisionRoute: typeof DiagnosticoRevisionRoute
  DiagnosticoIndexRoute: typeof DiagnosticoIndexRoute
  DiagnosticoPasoIdRoute: typeof DiagnosticoPasoIdRoute
}

const DiagnosticoRouteChildren: DiagnosticoRouteChildren = {
  DiagnosticoCierreRoute: DiagnosticoCierreRoute,
  DiagnosticoEspecializadosRoute: DiagnosticoEspecializadosRouteWithChildren,
  DiagnosticoListoRoute: DiagnosticoListoRoute,
  DiagnosticoMotorRoute: DiagnosticoMotorRoute,
  DiagnosticoProcesandoRoute: DiagnosticoProcesandoRoute,
  DiagnosticoResumenRoute: DiagnosticoResumenRoute,
  DiagnosticoRevisionRoute: DiagnosticoRevisionRoute,
  DiagnosticoIndexRoute: DiagnosticoIndexRoute,
  DiagnosticoPasoIdRoute: DiagnosticoPasoIdRoute,
}

const DiagnosticoRouteWithChildren = DiagnosticoRoute._addFileChildren(
  DiagnosticoRouteChildren,
)

interface PlanDeAccionRouteChildren {
  PlanDeAccionAccionRoute: typeof PlanDeAccionAccionRoute
  PlanDeAccionCierreRoute: typeof PlanDeAccionCierreRoute
  PlanDeAccionEntradaRoute: typeof PlanDeAccionEntradaRoute
  PlanDeAccionIndexRoute: typeof PlanDeAccionIndexRoute
  PlanDeAccionWorkspaceActividadRoute: typeof PlanDeAccionWorkspaceActividadRoute
}

const PlanDeAccionRouteChildren: PlanDeAccionRouteChildren = {
  PlanDeAccionAccionRoute: PlanDeAccionAccionRoute,
  PlanDeAccionCierreRoute: PlanDeAccionCierreRoute,
  PlanDeAccionEntradaRoute: PlanDeAccionEntradaRoute,
  PlanDeAccionIndexRoute: PlanDeAccionIndexRoute,
  PlanDeAccionWorkspaceActividadRoute: PlanDeAccionWorkspaceActividadRoute,
}

const PlanDeAccionRouteWithChildren = PlanDeAccionRoute._addFileChildren(
  PlanDeAccionRouteChildren,
)

interface ResultadosRouteChildren {
  ResultadosDimensionRoute: typeof ResultadosDimensionRoute
  ResultadosIndexRoute: typeof ResultadosIndexRoute
}

const ResultadosRouteChildren: ResultadosRouteChildren = {
  ResultadosDimensionRoute: ResultadosDimensionRoute,
  ResultadosIndexRoute: ResultadosIndexRoute,
}

const ResultadosRouteWithChildren = ResultadosRoute._addFileChildren(
  ResultadosRouteChildren,
)

interface RoadmapRouteChildren {
  RoadmapAccionRoute: typeof RoadmapAccionRoute
  RoadmapIndexRoute: typeof RoadmapIndexRoute
}

const RoadmapRouteChildren: RoadmapRouteChildren = {
  RoadmapAccionRoute: RoadmapAccionRoute,
  RoadmapIndexRoute: RoadmapIndexRoute,
}

const RoadmapRouteWithChildren =
  RoadmapRoute._addFileChildren(RoadmapRouteChildren)

interface SeguimientoRouteChildren {
  SeguimientoActividadRoute: typeof SeguimientoActividadRoute
  SeguimientoEntradaRoute: typeof SeguimientoEntradaRoute
  SeguimientoIndexRoute: typeof SeguimientoIndexRoute
}

const SeguimientoRouteChildren: SeguimientoRouteChildren = {
  SeguimientoActividadRoute: SeguimientoActividadRoute,
  SeguimientoEntradaRoute: SeguimientoEntradaRoute,
  SeguimientoIndexRoute: SeguimientoIndexRoute,
}

const SeguimientoRouteWithChildren = SeguimientoRoute._addFileChildren(
  SeguimientoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccesoRoute: AccesoRoute,
  ApoyoRoute: ApoyoRoute,
  AyudaRoute: AyudaRoute,
  CohorteRoute: CohorteRoute,
  ColaboracionRoute: ColaboracionRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemostracionRoute: DemostracionRoute,
  DiagnosticoRoute: DiagnosticoRouteWithChildren,
  InicioRoute: InicioRoute,
  ModaOrigenRoute: ModaOrigenRoute,
  PerfilRoute: PerfilRoute,
  PlanDeAccionRoute: PlanDeAccionRouteWithChildren,
  ResultadosRoute: ResultadosRouteWithChildren,
  RoadmapRoute: RoadmapRouteWithChildren,
  SeguimientoRoute: SeguimientoRouteWithChildren,
  ProyectoActividadRoute: ProyectoActividadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
