/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemostracionRouteImport } from './routes/demostracion'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanDeAccionRouteImport } from './routes/plan-de-accion'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAlertasRouteImport } from './routes/dashboard.alertas'
import { Route as DiagnosticoIndexRouteImport } from './routes/diagnostico.index'
import { Route as DiagnosticoCierreRouteImport } from './routes/diagnostico.cierre'
import { Route as DiagnosticoEspecializadosRouteImport } from './routes/diagnostico.especializados'
import { Route as DiagnosticoMotorRouteImport } from './routes/diagnostico.motor'
import { Route as DiagnosticoProcesandoRouteImport } from './routes/diagnostico.procesando'
import { Route as DiagnosticoResumenRouteImport } from './routes/diagnostico.resumen'
import { Route as DiagnosticoRevisionRouteImport } from './routes/diagnostico.revision'
import { Route as PlanDeAccionIndexRouteImport } from './routes/plan-de-accion.index'
import { Route as PlanDeAccionAccionRouteImport } from './routes/plan-de-accion.$accion'
import { Route as ResultadosIndexRouteImport } from './routes/resultados.index'
import { Route as ResultadosDimensionRouteImport } from './routes/resultados.$dimension'
import { Route as RoadmapIndexRouteImport } from './routes/roadmap.index'
import { Route as RoadmapAccionRouteImport } from './routes/roadmap.$accion'
import { Route as DashboardDimensionDimensionRouteImport } from './routes/dashboard.dimension.$dimension'
import { Route as DiagnosticoEspecializadosIndexRouteImport } from './routes/diagnostico.especializados.index'
import { Route as DiagnosticoEspecializadosEcommerceRouteImport } from './routes/diagnostico.especializados.ecommerce'
import { Route as DiagnosticoPasoIdRouteImport } from './routes/diagnostico.paso.$id'
import { Route as PlanDeAccionWorkspaceActividadRouteImport } from './routes/plan-de-accion.workspace.$actividad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemostracionRoute = DemostracionRouteImport.update({
  id: '/demostracion',
  path: '/demostracion',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanDeAccionRoute = PlanDeAccionRouteImport.update({
  id: '/plan-de-accion',
  path: '/plan-de-accion',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAlertasRoute = DashboardAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => DashboardRoute,
} as any)
const DiagnosticoIndexRoute = DiagnosticoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const DiagnosticoCierreRoute = DiagnosticoCierreRouteImport.update({
  id: '/cierre',
  path: '/cierre',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const DiagnosticoEspecializadosRoute =
  DiagnosticoEspecializadosRouteImport.update({
    id: '/especializados',
    path: '/especializados',
    getParentRoute: () => DiagnosticoRoute,
  } as any)
const DiagnosticoMotorRoute = DiagnosticoMotorRouteImport.update({
  id: '/motor',
  path: '/motor',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const DiagnosticoProcesandoRoute = DiagnosticoProcesandoRouteImport.update({
  id: '/procesando',
  path: '/procesando',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const DiagnosticoResumenRoute = DiagnosticoResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const DiagnosticoRevisionRoute = DiagnosticoRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const PlanDeAccionIndexRoute = PlanDeAccionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlanDeAccionRoute,
} as any)
const PlanDeAccionAccionRoute = PlanDeAccionAccionRouteImport.update({
  id: '/$accion',
  path: '/$accion',
  getParentRoute: () => PlanDeAccionRoute,
} as any)
const ResultadosIndexRoute = ResultadosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResultadosRoute,
} as any)
const ResultadosDimensionRoute = ResultadosDimensionRouteImport.update({
  id: '/$dimension',
  path: '/$dimension',
  getParentRoute: () => ResultadosRoute,
} as any)
const RoadmapIndexRoute = RoadmapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoadmapRoute,
} as any)
const RoadmapAccionRoute = RoadmapAccionRouteImport.update({
  id: '/$accion',
  path: '/$accion',
  getParentRoute: () => RoadmapRoute,
} as any)
const DashboardDimensionDimensionRoute =
  DashboardDimensionDimensionRouteImport.update({
    id: '/dimension/$dimension',
    path: '/dimension/$dimension',
    getParentRoute: () => DashboardRoute,
  } as any)
const DiagnosticoEspecializadosIndexRoute =
  DiagnosticoEspecializadosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DiagnosticoEspecializadosRoute,
  } as any)
const DiagnosticoEspecializadosEcommerceRoute =
  DiagnosticoEspecializadosEcommerceRouteImport.update({
    id: '/ecommerce',
    path: '/ecommerce',
    getParentRoute: () => DiagnosticoEspecializadosRoute,
  } as any)
const DiagnosticoPasoIdRoute = DiagnosticoPasoIdRouteImport.update({
  id: '/paso/$id',
  path: '/paso/$id',
  getParentRoute: () => DiagnosticoRoute,
} as any)
const PlanDeAccionWorkspaceActividadRoute =
  PlanDeAccionWorkspaceActividadRouteImport.update({
    id: '/workspace/$actividad',
    path: '/workspace/$actividad',
    getParentRoute: () => PlanDeAccionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demostracion': typeof DemostracionRoute
  '/diagnostico': typeof DiagnosticoRouteWithChildren
  '/inicio': typeof InicioRoute
  '/perfil': typeof PerfilRoute
  '/plan-de-accion': typeof PlanDeAccionRouteWithChildren
  '/resultados': typeof ResultadosRouteWithChildren
  '/roadmap': typeof RoadmapRouteWithChildren
  '/dashboard/alertas': typeof DashboardAlertasRoute
  '/diagnostico/cierre': typeof DiagnosticoCierreRoute
  '/diagnostico/especializados': typeof DiagnosticoEspecializadosRouteWithChildren
  '/diagnostico/motor': typeof DiagnosticoMotorRoute
  '/diagnostico/procesando': typeof DiagnosticoProcesandoRoute
  '/diagnostico/resumen': typeof DiagnosticoResumenRoute
  '/diagnostico/revision': typeof DiagnosticoRevisionRoute
  '/plan-de-accion/$accion': typeof PlanDeAccionAccionRoute
  '/resultados/$dimension': typeof ResultadosDimensionRoute
  '/roadmap/$accion': typeof RoadmapAccionRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/diagnostico/': typeof DiagnosticoIndexRoute
  '/plan-de-accion/': typeof PlanDeAccionIndexRoute
  '/resultados/': typeof ResultadosIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/dashboard/dimension/$dimension': typeof DashboardDimensionDimensionRoute
  '/diagnostico/especializados/ecommerce': typeof DiagnosticoEspecializadosEcommerceRoute
  '/diagnostico/paso/$id': typeof DiagnosticoPasoIdRoute
  '/plan-de-accion/workspace/$actividad': typeof PlanDeAccionWorkspaceActividadRoute
  '/diagnostico/especializados/': typeof DiagnosticoEspecializadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/demostracion': typeof DemostracionRoute
  '/inicio': typeof InicioRoute
  '/perfil': typeof PerfilRoute
  '/dashboard/alertas': typeof DashboardAlertasRoute
  '/diagnostico/cierre': typeof DiagnosticoCierreRoute
  '/diagnostico/motor': typeof DiagnosticoMotorRoute
  '/diagnostico/procesando': typeof DiagnosticoProcesandoRoute
  '/diagnostico/resumen': typeof DiagnosticoResumenRoute
  '/diagnostico/revision': typeof DiagnosticoRevisionRoute
  '/plan-de-accion/$accion': typeof PlanDeAccionAccionRoute
  '/resultados/$dimension': typeof ResultadosDimensionRoute
  '/roadmap/$accion': typeof RoadmapAccionRoute
  '/dashboard': typeof DashboardIndexRoute
  '/diagnostico': typeof DiagnosticoIndexRoute
  '/plan-de-accion': typeof PlanDeAccionIndexRoute
  '/resultados': typeof ResultadosIndexRoute
  '/roadmap': typeof RoadmapIndexRoute
  '/dashboard/dimension/$dimension': typeof DashboardDimensionDimensionRoute
  '/diagnostico/especializados/ecommerce': typeof DiagnosticoEspecializadosEcommerceRoute
  '/diagnostico/paso/$id': typeof DiagnosticoPasoIdRoute
  '/plan-de-accion/workspace/$actividad': typeof PlanDeAccionWorkspaceActividadRoute
  '/diagnostico/especializados': typeof DiagnosticoEspecializadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demostracion': typeof DemostracionRoute
  '/diagnostico': typeof DiagnosticoRouteWithChildren
  '/inicio': typeof InicioRoute
  '/perfil': typeof PerfilRoute
  '/plan-de-accion': typeof PlanDeAccionRouteWithChildren
  '/resultados': typeof ResultadosRouteWithChildren
  '/roadmap': typeof RoadmapRouteWithChildren
  '/dashboard/alertas': typeof DashboardAlertasRoute
  '/diagnostico/cierre': typeof DiagnosticoCierreRoute
  '/diagnostico/especializados': typeof DiagnosticoEspecializadosRouteWithChildren
  '/diagnostico/motor': typeof DiagnosticoMotorRoute
  '/diagnostico/procesando': typeof DiagnosticoProcesandoRoute
  '/diagnostico/resumen': typeof DiagnosticoResumenRoute
  '/diagnostico/revision': typeof DiagnosticoRevisionRoute
  '/plan-de-accion/$accion': typeof PlanDeAccionAccionRoute
  '/resultados/$dimension': typeof ResultadosDimensionRoute
  '/roadmap/$accion': typeof RoadmapAccionRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/diagnostico/': typeof DiagnosticoIndexRoute
  '/plan-de-accion/': typeof PlanDeAccionIndexRoute
  '/resultados/': typeof ResultadosIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/dashboard/dimension/$dimension': typeof DashboardDimensionDimensionRoute
  '/diagnostico/especializados/ecommerce': typeof DiagnosticoEspecializadosEcommerceRoute
  '/diagnostico/paso/$id': typeof DiagnosticoPasoIdRoute
  '/plan-de-accion/workspace/$actividad': typeof PlanDeAccionWorkspaceActividadRoute
  '/diagnostico/especializados/': typeof DiagnosticoEspecializadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayuda'
    | '/dashboard'
    | '/demostracion'
    | '/diagnostico'
    | '/inicio'
    | '/perfil'
    | '/plan-de-accion'
    | '/resultados'
    | '/roadmap'
    | '/dashboard/alertas'
    | '/diagnostico/cierre'
    | '/diagnostico/especializados'
    | '/diagnostico/motor'
    | '/diagnostico/procesando'
    | '/diagnostico/resumen'
    | '/diagnostico/revision'
    | '/plan-de-accion/$accion'
    | '/resultados/$dimension'
    | '/roadmap/$accion'
    | '/dashboard/'
    | '/diagnostico/'
    | '/plan-de-accion/'
    | '/resultados/'
    | '/roadmap/'
    | '/dashboard/dimension/$dimension'
    | '/diagnostico/especializados/ecommerce'
    | '/diagnostico/paso/$id'
    | '/plan-de-accion/workspace/$actividad'
    | '/diagnostico/especializados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayuda'
    | '/demostracion'
    | '/inicio'
    | '/perfil'
    | '/dashboard/alertas'
    | '/diagnostico/cierre'
    | '/diagnostico/motor'
    | '/diagnostico/procesando'
    | '/diagnostico/resumen'
    | '/diagnostico/revision'
    | '/plan-de-accion/$accion'
    | '/resultados/$dimension'
    | '/roadmap/$accion'
    | '/dashboard'
    | '/diagnostico'
    | '/plan-de-accion'
    | '/resultados'
    | '/roadmap'
    | '/dashboard/dimension/$dimension'
    | '/diagnostico/especializados/ecommerce'
    | '/diagnostico/paso/$id'
    | '/plan-de-accion/workspace/$actividad'
    | '/diagnostico/especializados'
  id:
    | '__root__'
    | '/'
    | '/ayuda'
    | '/dashboard'
    | '/demostracion'
    | '/diagnostico'
    | '/inicio'
    | '/perfil'
    | '/plan-de-accion'
    | '/resultados'
    | '/roadmap'
    | '/dashboard/alertas'
    | '/diagnostico/cierre'
    | '/diagnostico/especializados'
    | '/diagnostico/motor'
    | '/diagnostico/procesando'
    | '/diagnostico/resumen'
    | '/diagnostico/revision'
    | '/plan-de-accion/$accion'
    | '/resultados/$dimension'
    | '/roadmap/$accion'
    | '/dashboard/'
    | '/diagnostico/'
    | '/plan-de-accion/'
    | '/resultados/'
    | '/roadmap/'
    | '/dashboard/dimension/$dimension'
    | '/diagnostico/especializados/ecommerce'
    | '/diagnostico/paso/$id'
    | '/plan-de-accion/workspace/$actividad'
    | '/diagnostico/especializados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyudaRoute: typeof AyudaRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemostracionRoute: typeof DemostracionRoute
  DiagnosticoRoute: typeof DiagnosticoRouteWithChildren
  InicioRoute: typeof InicioRoute
  PerfilRoute: typeof PerfilRoute
  PlanDeAccionRoute: typeof PlanDeAccionRouteWithChildren
  ResultadosRoute: typeof ResultadosRouteWithChildren
  RoadmapRoute: typeof RoadmapRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demostracion': {
      id: '/demostracion'
      path: '/demostracion'
      fullPath: '/demostracion'
      preLoaderRoute: typeof DemostracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-de-accion': {
      id: '/plan-de-accion'
      path: '/plan-de-accion'
      fullPath: '/plan-de-accion'
      preLoaderRoute: typeof PlanDeAccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/alertas': {
      id: '/dashboard/alertas'
      path: '/alertas'
      fullPath: '/dashboard/alertas'
      preLoaderRoute: typeof DashboardAlertasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/diagnostico/': {
      id: '/diagnostico/'
      path: '/'
      fullPath: '/diagnostico/'
      preLoaderRoute: typeof DiagnosticoIndexRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/cierre': {
      id: '/diagnostico/cierre'
      path: '/cierre'
      fullPath: '/diagnostico/cierre'
      preLoaderRoute: typeof DiagnosticoCierreRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/especializados': {
      id: '/diagnostico/especializados'
      path: '/especializados'
      fullPath: '/diagnostico/especializados'
      preLoaderRoute: typeof DiagnosticoEspecializadosRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/motor': {
      id: '/diagnostico/motor'
      path: '/motor'
      fullPath: '/diagnostico/motor'
      preLoaderRoute: typeof DiagnosticoMotorRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/procesando': {
      id: '/diagnostico/procesando'
      path: '/procesando'
      fullPath: '/diagnostico/procesando'
      preLoaderRoute: typeof DiagnosticoProcesandoRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/resumen': {
      id: '/diagnostico/resumen'
      path: '/resumen'
      fullPath: '/diagnostico/resumen'
      preLoaderRoute: typeof DiagnosticoResumenRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/diagnostico/revision': {
      id: '/diagnostico/revision'
      path: '/revision'
      fullPath: '/diagnostico/revision'
      preLoaderRoute: typeof DiagnosticoRevisionRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/plan-de-accion/': {
      id: '/plan-de-accion/'
      path: '/'
      fullPath: '/plan-de-accion/'
      preLoaderRoute: typeof PlanDeAccionIndexRouteImport
      parentRoute: typeof PlanDeAccionRoute
    }
    '/plan-de-accion/$accion': {
      id: '/plan-de-accion/$accion'
      path: '/$accion'
      fullPath: '/plan-de-accion/$accion'
      preLoaderRoute: typeof PlanDeAccionAccionRouteImport
      parentRoute: typeof PlanDeAccionRoute
    }
    '/resultados/': {
      id: '/resultados/'
      path: '/'
      fullPath: '/resultados/'
      preLoaderRoute: typeof ResultadosIndexRouteImport
      parentRoute: typeof ResultadosRoute
    }
    '/resultados/$dimension': {
      id: '/resultados/$dimension'
      path: '/$dimension'
      fullPath: '/resultados/$dimension'
      preLoaderRoute: typeof ResultadosDimensionRouteImport
      parentRoute: typeof ResultadosRoute
    }
    '/roadmap/': {
      id: '/roadmap/'
      path: '/'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof RoadmapIndexRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/roadmap/$accion': {
      id: '/roadmap/$accion'
      path: '/$accion'
      fullPath: '/roadmap/$accion'
      preLoaderRoute: typeof RoadmapAccionRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/dashboard/dimension/$dimension': {
      id: '/dashboard/dimension/$dimension'
      path: '/dimension/$dimension'
      fullPath: '/dashboard/dimension/$dimension'
      preLoaderRoute: typeof DashboardDimensionDimensionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/diagnostico/especializados/': {
      id: '/diagnostico/especializados/'
      path: '/'
      fullPath: '/diagnostico/especializados/'
      preLoaderRoute: typeof DiagnosticoEspecializadosIndexRouteImport
      parentRoute: typeof DiagnosticoEspecializadosRoute
    }
    '/diagnostico/especializados/ecommerce': {
      id: '/diagnostico/especializados/ecommerce'
      path: '/ecommerce'
      fullPath: '/diagnostico/especializados/ecommerce'
      preLoaderRoute: typeof DiagnosticoEspecializadosEcommerceRouteImport
      parentRoute: typeof DiagnosticoEspecializadosRoute
    }
    '/diagnostico/paso/$id': {
      id: '/diagnostico/paso/$id'
      path: '/paso/$id'
      fullPath: '/diagnostico/paso/$id'
      preLoaderRoute: typeof DiagnosticoPasoIdRouteImport
      parentRoute: typeof DiagnosticoRoute
    }
    '/plan-de-accion/workspace/$actividad': {
      id: '/plan-de-accion/workspace/$actividad'
      path: '/workspace/$actividad'
      fullPath: '/plan-de-accion/workspace/$actividad'
      preLoaderRoute: typeof PlanDeAccionWorkspaceActividadRouteImport
      parentRoute: typeof PlanDeAccionRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAlertasRoute: typeof DashboardAlertasRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDimensionDimensionRoute: typeof DashboardDimensionDimensionRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAlertasRoute: DashboardAlertasRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDimensionDimensionRoute: DashboardDimensionDimensionRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface DiagnosticoEspecializadosRouteChildren {
  DiagnosticoEspecializadosEcommerceRoute: typeof DiagnosticoEspecializadosEcommerceRoute
  DiagnosticoEspecializadosIndexRoute: typeof DiagnosticoEspecializadosIndexRoute
}

const DiagnosticoEspecializadosRouteChildren: DiagnosticoEspecializadosRouteChildren =
  {
    DiagnosticoEspecializadosEcommerceRoute:
      DiagnosticoEspecializadosEcommerceRoute,
    DiagnosticoEspecializadosIndexRoute: DiagnosticoEspecializadosIndexRoute,
  }

const DiagnosticoEspecializadosRouteWithChildren =
  DiagnosticoEspecializadosRoute._addFileChildren(
    DiagnosticoEspecializadosRouteChildren,
  )

interface DiagnosticoRouteChildren {
  DiagnosticoCierreRoute: typeof DiagnosticoCierreRoute
  DiagnosticoEspecializadosRoute: typeof DiagnosticoEspecializadosRouteWithChildren
  DiagnosticoMotorRoute: typeof DiagnosticoMotorRoute
  DiagnosticoProcesandoRoute: typeof DiagnosticoProcesandoRoute
  DiagnosticoResumenRoute: typeof DiagnosticoResumenRoute
  DiagnosticoRevisionRoute: typeof DiagnosticoRevisionRoute
  DiagnosticoIndexRoute: typeof DiagnosticoIndexRoute
  DiagnosticoPasoIdRoute: typeof DiagnosticoPasoIdRoute
}

const DiagnosticoRouteChildren: DiagnosticoRouteChildren = {
  DiagnosticoCierreRoute: DiagnosticoCierreRoute,
  DiagnosticoEspecializadosRoute: DiagnosticoEspecializadosRouteWithChildren,
  DiagnosticoMotorRoute: DiagnosticoMotorRoute,
  DiagnosticoProcesandoRoute: DiagnosticoProcesandoRoute,
  DiagnosticoResumenRoute: DiagnosticoResumenRoute,
  DiagnosticoRevisionRoute: DiagnosticoRevisionRoute,
  DiagnosticoIndexRoute: DiagnosticoIndexRoute,
  DiagnosticoPasoIdRoute: DiagnosticoPasoIdRoute,
}

const DiagnosticoRouteWithChildren = DiagnosticoRoute._addFileChildren(
  DiagnosticoRouteChildren,
)

interface PlanDeAccionRouteChildren {
  PlanDeAccionAccionRoute: typeof PlanDeAccionAccionRoute
  PlanDeAccionIndexRoute: typeof PlanDeAccionIndexRoute
  PlanDeAccionWorkspaceActividadRoute: typeof PlanDeAccionWorkspaceActividadRoute
}

const PlanDeAccionRouteChildren: PlanDeAccionRouteChildren = {
  PlanDeAccionAccionRoute: PlanDeAccionAccionRoute,
  PlanDeAccionIndexRoute: PlanDeAccionIndexRoute,
  PlanDeAccionWorkspaceActividadRoute: PlanDeAccionWorkspaceActividadRoute,
}

const PlanDeAccionRouteWithChildren = PlanDeAccionRoute._addFileChildren(
  PlanDeAccionRouteChildren,
)

interface ResultadosRouteChildren {
  ResultadosDimensionRoute: typeof ResultadosDimensionRoute
  ResultadosIndexRoute: typeof ResultadosIndexRoute
}

const ResultadosRouteChildren: ResultadosRouteChildren = {
  ResultadosDimensionRoute: ResultadosDimensionRoute,
  ResultadosIndexRoute: ResultadosIndexRoute,
}

const ResultadosRouteWithChildren = ResultadosRoute._addFileChildren(
  ResultadosRouteChildren,
)

interface RoadmapRouteChildren {
  RoadmapAccionRoute: typeof RoadmapAccionRoute
  RoadmapIndexRoute: typeof RoadmapIndexRoute
}

const RoadmapRouteChildren: RoadmapRouteChildren = {
  RoadmapAccionRoute: RoadmapAccionRoute,
  RoadmapIndexRoute: RoadmapIndexRoute,
}

const RoadmapRouteWithChildren =
  RoadmapRoute._addFileChildren(RoadmapRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyudaRoute: AyudaRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemostracionRoute: DemostracionRoute,
  DiagnosticoRoute: DiagnosticoRouteWithChildren,
  InicioRoute: InicioRoute,
  PerfilRoute: PerfilRoute,
  PlanDeAccionRoute: PlanDeAccionRouteWithChildren,
  ResultadosRoute: ResultadosRouteWithChildren,
  RoadmapRoute: RoadmapRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
